version: '3.1'
services:
  db:
    image: mysql
    container_name: bd-mylibrary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-library:/var/lib/mysql

volumes:
  my-library: